// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPingHistory(arg1) {
  return window['go']['network']['NetworkService']['AddPingHistory'](arg1);
}

export function ClearPingHistory() {
  return window['go']['network']['NetworkService']['ClearPingHistory']();
}

export function GetPingHistory() {
  return window['go']['network']['NetworkService']['GetPingHistory']();
}

export function PingSubnet(arg1) {
  return window['go']['network']['NetworkService']['PingSubnet'](arg1);
}

export function RemovePingHistory(arg1) {
  return window['go']['network']['NetworkService']['RemovePingHistory'](arg1);
}

export function SetContext(arg1) {
  return window['go']['network']['NetworkService']['SetContext'](arg1);
}
