// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {context} from '../models';

export function AddPingHistory(arg1:string):Promise<Array<string>>;

export function ClearPingHistory():Promise<void>;

export function GetPingHistory():Promise<Array<string>>;

export function PingSubnet(arg1:string):Promise<Array<network.PingResult>>;

export function RemovePingHistory(arg1:string):Promise<Array<string>>;

export function SetContext(arg1:context.Context):Promise<void>;
