// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {crypto} from '../models';
import {context} from '../models';

export function DeleteCertificate(arg1:string):Promise<Array<crypto.CertRecord>>;

export function DeleteStoredKey(arg1:string):Promise<Array<crypto.StoredKey>>;

export function ExportCertificate(arg1:string):Promise<crypto.CertExport>;

export function ExportStoredKey(arg1:string):Promise<crypto.StoredKey>;

export function GenerateKeyPair(arg1:crypto.KeyGenRequest):Promise<crypto.KeyParseResult>;

export function IssueCertificate(arg1:crypto.CertIssueRequest):Promise<crypto.CertIssueResult>;

export function ListCertificates():Promise<Array<crypto.CertRecord>>;

export function ListStoredKeys():Promise<Array<crypto.StoredKey>>;

export function ParseCertificate(arg1:crypto.CertParseRequest):Promise<crypto.CertParseResult>;

export function ParseDER(arg1:crypto.DerParseRequest):Promise<crypto.DerParseResult>;

export function ParseKey(arg1:crypto.KeyParseRequest):Promise<crypto.KeyParseResult>;

export function RunAsymmetric(arg1:crypto.AsymmetricRequest):Promise<crypto.OperationResult>;

export function RunHash(arg1:crypto.HashRequest):Promise<crypto.OperationResult>;

export function RunSymmetric(arg1:crypto.SymmetricRequest):Promise<crypto.OperationResult>;

export function SetContext(arg1:context.Context):Promise<void>;
