// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCertificate(arg1) {
  return window['go']['crypto']['CryptoService']['DeleteCertificate'](arg1);
}

export function DeleteStoredKey(arg1) {
  return window['go']['crypto']['CryptoService']['DeleteStoredKey'](arg1);
}

export function ExportCertificate(arg1) {
  return window['go']['crypto']['CryptoService']['ExportCertificate'](arg1);
}

export function ExportStoredKey(arg1) {
  return window['go']['crypto']['CryptoService']['ExportStoredKey'](arg1);
}

export function GenerateKeyPair(arg1) {
  return window['go']['crypto']['CryptoService']['GenerateKeyPair'](arg1);
}

export function IssueCertificate(arg1) {
  return window['go']['crypto']['CryptoService']['IssueCertificate'](arg1);
}

export function ListCertificates() {
  return window['go']['crypto']['CryptoService']['ListCertificates']();
}

export function ListStoredKeys() {
  return window['go']['crypto']['CryptoService']['ListStoredKeys']();
}

export function ParseCertificate(arg1) {
  return window['go']['crypto']['CryptoService']['ParseCertificate'](arg1);
}

export function ParseDER(arg1) {
  return window['go']['crypto']['CryptoService']['ParseDER'](arg1);
}

export function ParseKey(arg1) {
  return window['go']['crypto']['CryptoService']['ParseKey'](arg1);
}

export function RunAsymmetric(arg1) {
  return window['go']['crypto']['CryptoService']['RunAsymmetric'](arg1);
}

export function RunHash(arg1) {
  return window['go']['crypto']['CryptoService']['RunHash'](arg1);
}

export function RunSymmetric(arg1) {
  return window['go']['crypto']['CryptoService']['RunSymmetric'](arg1);
}

export function SetContext(arg1) {
  return window['go']['crypto']['CryptoService']['SetContext'](arg1);
}
