// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GMSSLServerStatus() {
  return window['go']['other']['OtherService']['GMSSLServerStatus']();
}

export function RunGMSSLClientTest(arg1) {
  return window['go']['other']['OtherService']['RunGMSSLClientTest'](arg1);
}

export function SetContext(arg1) {
  return window['go']['other']['OtherService']['SetContext'](arg1);
}

export function Socks5Status() {
  return window['go']['other']['OtherService']['Socks5Status']();
}

export function StartGMSSLServer(arg1) {
  return window['go']['other']['OtherService']['StartGMSSLServer'](arg1);
}

export function StartSocks5Proxy(arg1) {
  return window['go']['other']['OtherService']['StartSocks5Proxy'](arg1);
}

export function StopGMSSLServer() {
  return window['go']['other']['OtherService']['StopGMSSLServer']();
}

export function StopSocks5Proxy() {
  return window['go']['other']['OtherService']['StopSocks5Proxy']();
}
