// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {other} from '../models';
import {context} from '../models';

export function CheckJavaRuntime():Promise<string>;

export function GMSSLServerStatus():Promise<other.GMSSLServerStatus>;

export function RenderPlantUML(arg1:other.PlantUMLRenderRequest):Promise<other.PlantUMLRenderResponse>;

export function RunGMSSLClientTest(arg1:other.GMSSLClientConfig):Promise<other.GMSSLClientResult>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Socks5Status():Promise<other.Socks5Status>;

export function StartGMSSLServer(arg1:other.GMSSLServerConfig):Promise<other.GMSSLServerStatus>;

export function StartSocks5Proxy(arg1:other.Socks5Config):Promise<other.Socks5Status>;

export function StopGMSSLServer():Promise<other.GMSSLServerStatus>;

export function StopSocks5Proxy():Promise<other.Socks5Status>;
